apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    {{- toYaml .Values.matchLabels | nindent 6 }}
  ports:
    - protocol: "{{.Values.service.protocol}}"
      port: {{.Values.service.port}}
      targetPort: {{ .Values.service.containerPort }}
  type: {{.Values.service.type}}