apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB: "mongodb://admin:23CZ3foMoJSRVuhF@cluster0-shard-00-00.i7ss7.mongodb.net:27017,cluster0-shard-00-01.i7ss7.mongodb.net:27017,cluster0-shard-00-02.i7ss7.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-8891xl-shard-0&authSource=admin&retryWrites=true&w=majority"
  CLOUDINARY_CLOUD_NAME: "dkiwa73vl"
  CLOUDINARY_API_KEY: "751534111462923"
  CLOUDINARY_API_SECRET: "dH1LoTAN"
  STRIPE_SECRET: "sk_test_51IhUG2SFyEg8AS59LGp3rpJFmXsoCpYUbYC49JbBtpErx0Qnv59d9nNCU4kbO2Jy9iaelaqgDBDBurscgKK4zW7C00ba5wVLYg"